#!/bin/bash
set -xeuo pipefail

if [[ $1 == init ]]; then
    mkdir -p db && initdb db
    pg_ctl -D db -l db/logfile start

    psql -c 'CREATE EXTENSION postgis;'
    psql < init.sql
fi

if [[ $1 == start ]]; then
    pg_ctl -D db -l db/logfile start
fi


if [[ $1 == stop ]]; then
    pg_ctl -D db -l db/logfile stop
fi
