Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/eoan64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y \
      qgis freecad \
      stow openbox-lxde-session lxterminal tightvncserver ipython3 \
      tree
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    mkdir -p .ssh .vnc
    curl https://github.com/motiejus.keys >> .ssh/authorized_keys
    git clone https://github.com/motiejus/dotfiles.git .dotfiles
    (cd .dotfiles && stow bash tmux vim)
  SHELL

  # my geom: 2560x1600
  # vncserver -geometry 1280x800 small window
  # vncserver -geometry 1920x1200 small letters
  # vncserver -geometry 1536x960 great
  config.vm.provision "file", source: "xsession", destination: ".vnc/xsession"

end
