Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/disco64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
  
  # my geom: 2560x1600
  # vncserver -geometry 1280x800 small window
  # vncserver -geometry 1920x1200 small letters
  # vncserver -geometry 1536x960 great
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p .ssh; curl https://github.com/motiejus.keys >> .ssh/authorized_keys
    apt-get update
    apt-get install -y qgis \
      openbox-lxde-session lxterminal tightvncserver
  SHELL
end
